# Kubernetes DaemonSet for tcd
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: tcd
  labels:
    k8s-app: tcd
spec:
  template:
    metadata:
      name:  tcd
      labels:
        k8s-app: tcd
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name:  tcd
        image: albanc/tcd:demo1
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 50m
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: dbus-sock
          mountPath: /var/run/dbus/system_bus_socket
        - name: run
          mountPath: /run
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: dbus-sock
        hostPath:
          path: /var/run/dbus/system_bus_socket
      - name: run
        hostPath:
          path: /run
